services:
      boxerdeploy:
              build: .
              ports: 
                - '80:80'
              container_name: apache2-boxer-deploy
              volumes:
                - myapp:/var/www/html/
              network_mode:
                  bridge

volumes:
      myapp: